// SPDX-License-Identifier: GPL-2.0

#ifndef YOS_NETWORKD_CONFIG_H
#define YOS_NETWORKD_CONFIG_H

#include <stdint.h>

#define NETD_IPC_CLIENTS_INITIAL 8
#define NETD_IPC_CLIENTS_MAX 256

#define NETD_ARP_CACHE_INITIAL 32
#define NETD_ARP_CACHE_MAX 1024
#define NETD_ARP_ENTRY_TTL_MS 300000

#define NETD_FRAME_MAX 1600u
#define NETD_JUMBO_FRAME_MAX 9000u

#define NETD_ICMP_DATA_SIZE 56u

#define NETD_ARP_TIMEOUT_MS 800u
#define NETD_ARP_RETRY_COUNT 3

#define NETD_PING_ID 0x1234u

#define NETD_DEFAULT_IP   0x0A00020Fu
#define NETD_DEFAULT_MASK 0xFFFFFF00u
#define NETD_DEFAULT_GW   0x0A000202u
#define NETD_DEFAULT_DNS  0x08080808u

#define NETD_TCP_RX_BUF_MIN 4096u
#define NETD_TCP_RX_BUF_DEFAULT 65536u
#define NETD_TCP_RX_BUF_MAX 1048576u

#define NETD_TCP_TX_BUF_MIN 4096u
#define NETD_TCP_TX_BUF_DEFAULT 65536u
#define NETD_TCP_TX_BUF_MAX 1048576u

#define NETD_TCP_CONN_INITIAL 16
#define NETD_TCP_CONN_MAX 4096

#define NETD_TCP_MSS_DEFAULT 1200u
#define NETD_TCP_MSS_MAX 1460u

#define NETD_TCP_WINDOW_SCALE 7

#define NETD_TCP_CONN_TIMEOUT_MS 120000
#define NETD_TCP_IDLE_TIMEOUT_MS 300000
#define NETD_TCP_TIMEWAIT_MS 30000

#define NETD_TCP_RETRANSMIT_TIMEOUT_MS 1000
#define NETD_TCP_MAX_RETRIES 5

#define NETD_DNS_CACHE_SIZE 128
#define NETD_DNS_CACHE_TTL_MS 300000
#define NETD_DNS_MAX_WAITS 64

#define NETD_HTTP_MAX_JOBS 32
#define NETD_HTTP_MAX_REDIRECTS 5
#define NETD_HTTP_TIMEOUT_MS 30000
#define NETD_HTTP_BUFFER_SIZE 8192

#define NETD_POLL_TIMEOUT_MS 10

#define NETD_STATS_ENABLED 1

#define NETD_LOG_LEVEL_ERROR 0
#define NETD_LOG_LEVEL_WARN 1
#define NETD_LOG_LEVEL_INFO 2
#define NETD_LOG_LEVEL_DEBUG 3

#define NETD_LOG_LEVEL NETD_LOG_LEVEL_INFO

#define NETD_ENABLE_ZERO_COPY 1

#define NETD_ENABLE_TCP_FAST_OPEN 0

#define NETD_ENABLE_TCP_TIMESTAMPS 1

#define NETD_ENABLE_CONGESTION_CONTROL 1

#endif